module.exports = {
  defaultNetwork: 'localnet',

  networks: {
    localnet: {
      host: 'localhost',
      adminPort: 5002,
      ledgerPort: 5001,
      httpPort: 7575,
      uploadVia: 'admin',
      vetOnUpload: true,
      jwtUserId: 'ledger-api-user',
      jwtAudience: 'https://canton.network.global',
      scriptUserId: 'ledger-api-user',
      additionalDars: ['./vendor/some-lib-1.0.0.dar'],
      includePackages: [],
      excludePackages: ['./tests', 'my-app-tests'],
      parties: ['Alice', 'Bob'],
      users: [
        {
          userId: 'ledger-api-user',
          parties: ['Alice', 'Bob'],
          rights: ['CanActAs', 'CanReadAs'],
        },
      ],
    },


    devnet: {
      host: '127.0.0.1',
      ledgerPort: 5001,
      httpPort: 7575,
      adminPort: 5002,
      grpcAuthority: 'grpc-ledger-api.localhost',
      httpHost: 'json-ledger-api.localhost',
      httpUseTls: false,
      uploadVia: 'ledger',
      vetOnUpload: true,
      oauth2: {
        tokenUrl: 'https://YOUR_TENANT.auth0.com/oauth/token',
        clientId: 'YOUR_CLIENT_ID',
        clientSecretEnv: 'DEVNET_OAUTH_CLIENT_SECRET',
        audience: 'https://canton.network.global',
      },
      tunnel: {
        ssh: {
          host: 'dev-server.example.com',
          user: 'ubuntu',
          // port: 22,
          identityFile: '~/.ssh/id_ed25519',
          forwards: [
            { localPort: 5001, remoteHost: '127.0.0.1', remotePort: 80 },
            { localPort: 7575, remoteHost: '127.0.0.1', remotePort: 80 },
            // { localPort: 5002, remoteHost: '127.0.0.1', remotePort: 80 },
          ],
        },
      },
      parties: ['Operator'],
      users: [
        {
          userId: 'app-operator',
          parties: ['Operator'],
          rights: ['CanActAs', 'CanReadAs'],
        },
      ],
      additionalDars: [],
      excludePackages: [],
    },

    testnet: {
      host: 'testnet-validator.example.com',
      adminPort: 5002,
      ledgerPort: 443,
      httpPort: 443,
      uploadVia: 'ledger',
      tls: true,
      tlsCertFile: './certs/testnet-ca.pem',
      httpUseTls: true,
      grpcAuthority: 'grpc-ledger-api.testnet.example.com',
      adminGrpcAuthority: 'admin-api.testnet.example.com',
      httpHost: 'json-ledger-api.testnet.example.com',
      synchronizerId: 'global-domain::1220...',
      tokenFile: './.tokens/testnet.jwt',
      vetOnUpload: false,
      parties: [],
      users: [],
      additionalDars: [],
      excludePackages: ['./tests'],
    },

    mainnet: {
      host: 'mainnet-validator.example.com',
      adminPort: 5002,
      ledgerPort: 443,
      httpPort: 443,
      uploadVia: 'ledger',
      tls: true,
      httpUseTls: true,
      grpcAuthority: 'grpc-ledger-api.example.com',
      synchronizerId: 'global-domain::1220...',
      tokenCommand: 'vault read -field=token secret/canton/mainnet-jwt',
      vetOnUpload: false,
      includePackages: ['./app'],
      excludePackages: ['./tests'],
      additionalDars: [],
      parties: ['AppOperator'],
      users: [
        {
          userId: 'app-operator',
          parties: ['AppOperator'],
          rights: ['CanActAs', 'CanReadAs'],
        },
      ],
    },
  },
};
