import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { input, confirm } from '@inquirer/prompts';

function portInput(message: string, hint: string): Promise<string> {
  return input({
    message: `${message} ${chalk.gray(`(default: ${hint})`)}`,
    validate: (v) => {
      if (!v) return true;
      const n = parseInt(v, 10);
      return (!isNaN(n) && n > 0 && n < 65536) || 'Must be a valid port (1–65535)';
    },
  });
}

export async function runInit(): Promise<void> {
  console.log(chalk.bold('\n  canton-deploy init'));
  console.log(chalk.gray('  LocalNet profile; Admin API upload.\n'));

  const configPath = path.join(process.cwd(), 'canton-deploy.config.js');
  if (fs.existsSync(configPath)) {
    const overwrite = await confirm({
      message: 'canton-deploy.config.js already exists. Overwrite?',
      default: false,
    });
    if (!overwrite) {
      console.log(chalk.gray('\n  Aborted.\n'));
      return;
    }
  }

  const localnetHost = await input({ message: 'LocalNet host:', default: 'localhost' });
  const localnetAdmin = await portInput('LocalNet Admin API port:', '5002');
  const localnetLedger = await portInput('LocalNet Ledger API port:', '5001');
  const localnetHttp = await portInput('LocalNet JSON API port:', '7575');

  const content = `// canton-deploy.config.js (generated by canton-deploy init)
// Upload path: Admin API (PackageService.UploadDar).

module.exports = {
  defaultNetwork: "localnet",

  networks: {
    localnet: {
      host: "${localnetHost}",
      adminPort: ${localnetAdmin || 5002},
      ledgerPort: ${localnetLedger || 5001},
      httpPort: ${localnetHttp || 7575},
    },
  },
};
`;

  fs.writeFileSync(configPath, content, 'utf8');

  console.log(chalk.green(`\n  Created: ${configPath}`));
  console.log(chalk.gray('\n  Next steps:'));
  console.log(chalk.gray('    canton-deploy status --network localnet'));
  console.log(chalk.gray('    canton-deploy deploy --network localnet\n'));
}
